const projects=[
{name:"Beetlecat",location:"Atlanta, Georgia",type:"Hospitality",summary:"Designed as a warm, layered hospitality space, Beetlecat required a balance of precision and personality. Freeman GC led construction with a focus on collaboration, sequencing, and detail—bringing together materials, systems, and finishes in a way that feels cohesive and lived-in. The result is a space that enhances the rhythm of service while inviting guests to linger.",details:"",quote:"Freeman treated our project like it mattered — and it showed in the finished work.",credits:[["Client","Rocket Farm Restaurants"],["Photography","Jared Swafford"],["Interior Design","Chuck Marie Studio"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690112c66907ba02f5612747_Beetlecat%20Thumb%20Freeman%20General%20Contractors_HP.jpg"]},
{name:"The Optimist",location:"Atlanta, Georgia",type:"Hospitality",summary:"Freeman General Contracting was given the opportunity to refresh the Oyster Bar at the highly esteemed restaurant in Atlanta, The Optimist. This project was on a tight deadline of 3 weeks. FGC finished on time and under budget. This project boasts ultra high-end finishes - custom radius window, radius tile around oven, custom millwork pieces, custom stainless steel pieces. This project had it all.",details:"",quote:"",credits:[["Client","Rocket Farm Restaurants"],["Photography","Jared Swafford"],["Interior Design","Chuck Marie Studio"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916c3cc412995612baf28e4_The%20Optimist_Freeman%20General%20Contractors%200.jpg"]},
{name:"Barnsley Gardens",location:"Adairsville, Georgia",type:"Hospitality",summary:"This Barnsley project defined by subtlety, sequencing, and respect for place. Freeman approached construction with a focus on precision and care, allowing materials, landscape, and structure to work together seamlessly. The result is an environment that feels settled and enduring, shaped as much by restraint as by craftsmanship.",details:"",quote:"",credits:[["Client","Barnsley Resorts"],["Photography","Jared Swafford"],["Interior Design","Chuck Marie Studio"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916c7910f0d654dd4daa28f_Barnsley%20Gardens_Freeman%20General%20Contractors%201.jpg"]},
{name:"Bocado Pizza",location:"Atlanta, Georgia",type:"Commercial",summary:"Bocado Pizza was a full commercial renovation boasting new custom millwork, a new bar area, all new flooring in the main dining and kitchen area, as well as new finishes throughout. Brand new outdoor seating area completed as well.",details:"",quote:"Professional, responsive, and deeply knowledgeable. Freeman understands both construction and the importance of trust.",credits:[["Client","Bocado Pizza"],["Photography","Freeman GC"],["Interior Design","Interior Designer"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db75041d703e9a18d4085_Bocado%20Pizza_Interior%20Seating.jpeg"]},
{name:"Savi Provisions",location:"Emory Village, Atlanta",type:"Retail",summary:"At Savi Provisions, construction plays a supporting role in the customer experience. Freeman worked closely with the project team to execute a space that balances durability with refinement—allowing materials, layout, and flow to work together naturally.",details:"",quote:"",credits:[["Client","Savi Provisions"],["Budget","$850k"],["Interior Design","Interior Designer"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db4c97f14414f0e9997d7_Freeman%20General%20Contractors_Savi-Provisions_Emory-Village.jpg"]},
{name:"O-Ku Atlanta",location:"Atlanta, Georgia",type:"Hospitality",summary:"O-Ku Atlanta was a full commercial renovation boasting new custom millwork, a refresh to the bar area, all new flooring in the main dining and kitchen area, as well as updating the finishes throughout. This project was completed on a tight 3-week schedule.",details:"",quote:"",credits:[["Client","O-Ku Atlanta"],["Photography","Freeman GC"],["Interior Design","Chuck Marie Studio"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db404e2c8b7283f87b2cf_O-Ku%20Atlanta_Omotenashi%20Sign.jpeg"]},
{name:"La Cresta on Main",location:"Blue Ridge, Georgia",type:"High-End Residential",summary:"LaCresta On Main is a high-end residential project located in the scenic town of Blue Ridge, GA. This project consists of four luxurious 3-story units, each featuring spacious two-car garages and top-of-the-line finishes.",details:"LaCresta On Main showcases exceptional craftsmanship and attention to detail. The units are designed with contemporary architecture, incorporating open floor plans, high ceilings, and premium materials. Each unit is equipped with state-of-the-art appliances, custom cabinetry, and elegant fixtures, providing residents with a sophisticated and comfortable living experience.",quote:"",credits:[["Location","Blue Ridge, GA"],["Budget","$3.1 million"],["Project Type","New Construction Residential"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db50754b35340d6a11efd_FGC_La%20Cresta%20on%20Main_Exterior.jpeg"]},
{name:"Cleveland Surgery Center",location:"Cleveland, Tennessee",type:"Healthcare",summary:"Designed to support both clinical precision and patient comfort, Cleveland Surgery Center was constructed with care at every level. Freeman approached the project with a focus on coordination, durability, and long-term performance—creating a space that functions seamlessly behind the scenes.",details:"",quote:"",credits:[["Client","Interventional Pain Consultants"],["Budget","$1.1M"],["Interior Design","Chuck Marie Studio"],["Location","Cleveland, TN"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db51e0255304cdedbe097_Cleveland%20Surgery%20Center_FGC.jpeg"]},
{name:"Dalton Surgery Center",location:"Dalton, Georgia",type:"Healthcare",summary:"Designed to support both clinical precision and patient comfort, Dalton Surgery Center was constructed with care at every level. Freeman approached the project with a focus on coordination, durability, and long-term performance—creating a space that functions seamlessly behind the scenes.",details:"",quote:"",credits:[["Client","Interventional Pain Consultants"],["Photography","Freeman GC"],["Interior Design","Interior Designer"],["Total sq. ft.","2,000+"],["Complete","2024"]],images:["https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/692db53cb73187579c63c249_Dalton%20Surgery%20Center_FGC.jpeg"]}
];

const archive=[
"https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960ced1751e716bfb0d1_Tool%2010.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960db4daa5efe493b52d_Tool%2018.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916ba25fd36f33f132811ca_Tool%2021.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913963dedf7618fdeb28918_Tool%2011.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960c4de32e0b5a2bf0b2_Tool%209.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916ba25de1a366bd6999424_Tool%2023.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916ba250384493efbdd53ea_Tool%2024.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916baff2b5b2cf2c2f78554_Tool%2028.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e50c7615afc9742977885_Service%202.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960d4238c7ae0ca2ac76_Tool%2020.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916ba25e9cf0be4b68cae04_Tool%2025.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6916ba25070e98e98beba47b_Tool%2026.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e4e9110211ed9a915136a_Service%201.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960c51a29b87eb417808_Tool%208.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960c8313941195fa1174_Tool%2015.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960d21dba16dfe52ed43_Tool%2019.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960d3298c1cdfac1a6f6_Tool%2016.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/6913960c24b9f5d532655343_Tool%2012.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e25931f3a34d1ea4e0da6_Tool%202.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e25932359baba240b0b8f_Tool%204.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e2593b29db7bf57b890eb_Tool%206.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e2593ba81ccc61c685dae_Tool%205.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e2592217a88f2ecfa62e7_Tool%203.png","https://cdn.prod.website-files.com/666b9585b7fd3bd24dfbba73/690e259371dd2e5b56411391_Tool%201.png"
];

const people=[["Gabe Freeman","President","Gabe has been in the construction industry for Eight years. He worked as a Project Manager for four years, mastering the backend operations of General Contracting. The following Three years were spent in a business partnership focused on ground-up construction of convenience stores, where he gained invaluable hands-on and practical experience. For the past year, Gabe has leveraged his comprehensive industry experience to confidently lead his newest endeavor, Freeman General Contracting."]];

const services=[
["Design + Build","Good building starts with shared decisions. We work with owners, architects and engineers to align design, scope and budget early, then coordinate materials and details through construction. The aim is a place that serves its people well, with the thinking behind each decision carried into the work."],
["Construction Management","Care shows up in the daily work: coordinating trades, tracking decisions and keeping owners informed. We bring schedules, cost updates, field documentation and open items into the conversation, so the team understands what is happening, what has changed and what needs attention next."],
["Commercial Construction","Restaurants, retail and hospitality spaces have to work for the people who run them and the guests they welcome. We coordinate construction around those needs, from trade sequencing and equipment to the finishes people touch. Constructing Hospitality means bringing that same consideration to the owner's experience of building."],
["High End Residential Construction","A home should feel considered long after move-in. We work with homeowners and their design teams to carry material choices, custom details and everyday needs through construction. Built for Generations begins with careful coordination, respect for the home and attention to the work behind the finished surfaces."]
];

const faqs=[
["How long will my project take?","The schedule depends on scope, existing conditions, permits and material lead times. We work through those factors with you before setting expectations, then communicate changes as they arise. A focused renovation and a six-month undertaking call for different plans; both need clear sequencing and timely decisions."],
["How do you manage costs and changes?","We start by aligning scope and budget, then track decisions as the work develops. When conditions or selections change, we explain the effect on cost and schedule and document the agreed direction. Clear records help owners make informed choices and keep the team working from the same information."],
["How will I know what is happening on site?","Progress updates, field photos and records of decisions make the work easier to follow. We explain what has moved forward, what needs attention and which decisions are coming next. That continuity matters over months of construction, when details need to stay clear from one conversation to the next."],
["What does Constructing Hospitality mean?","It means caring for people throughout the build: listening to owners, respecting the design team and trades, and considering how a place will be used. Thoughtful sequencing, clear communication and attention to details are part of that service, whether we are building a restaurant, a business or a home."]
];

function showView(id){
  document.querySelectorAll('.view').forEach(v=>{const active=v.id===id;v.classList.toggle('active',active);v.setAttribute('aria-hidden',String(!active));});
  document.querySelectorAll('nav button').forEach(b=>{const active=b.dataset.view===id;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});
  if(window.innerWidth<=700)window.scrollTo({top:0,behavior:'instant'});
}
homeBtn.onclick=()=>showView('home');
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));

let current=0;const plist=document.getElementById('projectList');
function showProject(i){
  current=i;const p=projects[i];
  [...plist.children].forEach((b,j)=>{const active=j===i;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
  pTop.textContent=`${p.location} · ${p.type} · Project ${String(i+1).padStart(2,'0')} / 09`;
  pName.textContent=p.name;pSummary.textContent=p.summary;
  pDetails.textContent=p.details||'';pDetails.style.display=p.details?'block':'none';
  pQuote.textContent=p.quote?`“${p.quote}”`:'';pQuote.style.display=p.quote?'block':'none';
  pImage.style.opacity=0;pImage.alt=`${p.name} — ${p.location}`;
  setTimeout(()=>{pImage.src=p.images[0];pImage.style.opacity=1},60);
  pCap.textContent=`${p.name} · ${p.location}`;
  quickfacts.innerHTML=p.credits.map(x=>`<div class="qf"><div class="k">${x[0]}</div><div class="v">${x[1]}</div></div>`).join('');
}
projects.forEach((p,i)=>{const b=document.createElement('button');b.className='proj-btn'+(i===0?' active':'');b.type='button';b.setAttribute('aria-label',`View ${p.name}`);b.setAttribute('aria-pressed',String(i===0));b.innerHTML=`<span class="n">${String(i+1).padStart(2,'0')}</span><span class="nm">${p.name}</span>`;b.onclick=()=>showProject(i);plist.appendChild(b)});showProject(0);

document.querySelectorAll('.subnav button').forEach(b=>{b.type='button';b.onclick=()=>{document.querySelectorAll('.subnav button').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');document.querySelectorAll('.subview').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.sub).classList.add('active')}});
document.querySelector('.subnav button.active')?.setAttribute('aria-selected','true');

services.forEach(s=>{const d=document.createElement('div');d.className='service-card';d.innerHTML=`<h3>${s[0]}</h3><p>${s[1]}</p>`;servicesList.appendChild(d)});
function showPerson(i){personName.textContent=people[i][0];personRole.textContent=people[i][1];personCopy.textContent=people[i][2]}showPerson(0);
faqs.forEach(f=>{const d=document.createElement('div');d.className='faq-item';d.innerHTML=`<h4>${f[0]}</h4><p>${f[1]}</p>`;faqList.appendChild(d)});
archive.forEach((src,i)=>{const b=document.createElement('button');b.type='button';b.className='archive-cell';b.setAttribute('aria-label',`Freeman field archive image ${i+1}`);b.innerHTML=`<img src="${src}" alt="Freeman field archive ${i+1}" loading="lazy" decoding="async"><span>${String(i+1).padStart(3,'0')}</span>`;archiveGrid.appendChild(b)});

document.querySelectorAll('.ptype button').forEach(b=>{b.type='button';b.onclick=()=>{document.querySelectorAll('.ptype button').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true')}});
document.querySelector('.ptype button.active')?.setAttribute('aria-pressed','true');

const sendButton=document.querySelector('.send');
if(sendButton){sendButton.type='button';sendButton.addEventListener('click',()=>{const fields=[...document.querySelectorAll('.form .field')];const name=fields[0]?.value?.trim()||'';const email=fields[1]?.value?.trim()||'';const phone=fields[2]?.value?.trim()||'';const message=fields[3]?.value?.trim()||'';const projectType=document.querySelector('.ptype button.active')?.textContent?.trim()||'';const subject=encodeURIComponent(`Project inquiry${name?` — ${name}`:''}`);const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\nPhone: ${phone}\nProject type: ${projectType}\n\n${message}`);window.location.href=`mailto:gabe@freemangc.com?subject=${subject}&body=${body}`;});}

const mobileHeaderStyle=document.createElement('style');
mobileHeaderStyle.textContent=`@media(max-width:700px){header{min-height:94px!important;grid-template-rows:48px 46px!important}.brand .logo{display:none!important}.brand{gap:0!important}.brand .mark{width:29px!important}.header-mark{font-size:8px!important;letter-spacing:.09em!important}nav button{padding:12px 0 9px!important}}`;
document.head.appendChild(mobileHeaderStyle);

showView('home');
